spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/chuangsys?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

pagehelper:
  helperDialect: Mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


